---
- name: Configure NVMe disk with LVM
  hosts: your_target_hosts
  become: yes
  tasks:
    - name: Install LVM2 package
      package:
        name: lvm2
        state: present

    - name: Create Physical Volume
      lvg:
        pvs: /dev/nvme0n1
        vg: vg_nvme
        state: present

    - name: Create Logical Volume for Docker
      lvol:
        vg: vg_nvme
        lv: lv_docker
        size: 40g
        state: present

    - name: Create Logical Volume for Rancher
      lvol:
        vg: vg_nvme
        lv: lv_rancher
        size: 40g
        state: present

    - name: Create Logical Volume for Opt
      lvol:
        vg: vg_nvme
        lv: lv_opt
        size: 20g
        state: present

    - name: Create Logical Volume for usr_local 
      lvol:
        vg: vg_nvme
        lv: lv_usr_local
        size: 10g
        state: present

    - name: Create filesystem on lv_docker
      filesystem:
        fstype: xfs
        dev: /dev/vg_nvme/lv_docker

    - name: Create filesystem on lv_rancher
      filesystem:
        fstype: xfs
        dev: /dev/vg_nvme/lv_rancher

    - name: Create filesystem on lv_opt
      filesystem:
        fstype: xfs
        dev: /dev/vg_nvme/lv_opt

    - name: Create filesystem on lv_usr_local
      filesystem:
        fstype: xfs
        dev: /dev/vg_nvme/lv_usr_local

    - name: Create mount point for Docker
      file:
        path: /var/lib/docker
        state: directory

    - name: Create mount point for Rancher
      file:
        path: /var/lib/rancher
        state: directory

    - name: Create mount point for Opt 
      file:
        path: /opt
        state: directory

    - name: Create mount point for usr_local 
      file:
        path: /usr/local
        state: directory

    - name: Mount lv_docker
      mount:
        path: /var/lib/docker
        src: /dev/vg_nvme/lv_docker
        fstype: xfs
        state: mounted

    - name: Mount lv_rancher
      mount:
        path: /var/lib/rancher
        src: /dev/vg_nvme/lv_rancher
        fstype: xfs
        state: mounted

    - name: Mount lv_opt
      mount:
        path: /opt
        src: /dev/vg_nvme/lv_opt
        fstype: xfs
        state: mounted

    - name: Mount lv_usr-local
      mount:
        path: /usr/local
        src: /dev/vg_nvme/lv_usr_local
        fstype: xfs
        state: mounted
