---
- name: Update nvpmodel to mode 8
  hosts: all
  become: true

  tasks:
    - name: Set nvpmodel to mode 8
      ansible.builtin.command: nvpmodel -m 8
      register: nvpmodel_result
      changed_when: "'Successfully set' in nvpmodel_result.stdout"
      failed_when:
        - nvpmodel_result.rc != 0
        - "'Successfully set' not in nvpmodel_result.stdout"

    - name: Display nvpmodel result
      ansible.builtin.debug:
        var: nvpmodel_result.stdout_lines

    - name: Verify nvpmodel mode
      ansible.builtin.command: nvpmodel -q
      register: nvpmodel_verify
      changed_when: false

    - name: Display current nvpmodel mode
      ansible.builtin.debug:
        var: nvpmodel_verify.stdout_lines
...
