---
- name: Configure Volumes, Filesystems, and Mounts
  hosts: all
  become: yes
  tasks:

    - name: Create Logical Volume for Docker
      lvol:
        vg: vg_nvme
        lv: lv_docker
        size: 25g
        state: present

    - name: Create Logical Volume for Rancher
      lvol:
        vg: vg_nvme
        lv: lv_rancher
        size: 25g
        state: present

    - name: Create Logical Volume for Opt
      lvol:
        vg: vg_nvme
        lv: lv_opt
        size: 15g
        state: present

    - name: Create Logical Volume for usr_local 
      lvol:
        vg: vg_nvme
        lv: lv_usr_local
        size: 10g
        state: present

    - name: Create filesystem on lv_docker
      filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_docker

    - name: Create filesystem on lv_rancher
      filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_rancher

    - name: Create filesystem on lv_opt
      filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_opt

    - name: Create filesystem on lv_usr_local
      filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_usr_local

    - name: Create mount point for Docker
      file:
        path: /var/lib/docker
        state: directory

    - name: Create mount point for Rancher
      file:
        path: /var/lib/rancher
        state: directory

    - name: Create mount point for Opt 
      file:
        path: /opt
        state: directory

    - name: Create mount point for usr_local 
      file:
        path: /usr/local
        state: directory

    - name: Mount lv_docker
      mount:
        path: /var/lib/docker
        src: /dev/vg_nvme/lv_docker
        fstype: ext4
        state: mounted

    - name: Mount lv_rancher
      mount:
        path: /var/lib/rancher
        src: /dev/vg_nvme/lv_rancher
        fstype: ext4
        state: mounted

    - name: Mount lv_opt
      mount:
        path: /opt
        src: /dev/vg_nvme/lv_opt
        fstype: ext4
        state: mounted

    - name: Mount lv_usr-local
      mount:
        path: /usr/local
        src: /dev/vg_nvme/lv_usr_local
        fstype: ext4
        state: mounted


# /home has to be treated differently

    - name: Create Logical Volume for Home
      lvol:
        vg: vg_nvme
        lv: lv_home
        size: 20g
        state: present

    - name: Create filesystem on lv_home
      filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_home

    - name: Create a temporary mount point
      file:
        path: /mnt/newhome
        state: directory

    - name: Mount lv_home in temporary filesystem
      mount:
        path: /mnt/newhome
        src: /dev/vg_nvme/lv_home
        fstype: ext4
        state: mounted

    - name: Synchronize data from original /home to new volume
      synchronize:
        src: /home/
        dest: /mnt/newhome/
        archive: yes
        recursive: yes

    - name: Unmount the temporary mount point
      mount:
        path: /mnt/newhome
        state: unmounted

    - name: Remove the temporary mount point
      file:
        path: /mnt/newhome
        state: absent

    - name: Backup original /home
      command: mv /home /home.bak

    - name: Create mount point for Home
      file:
        path: /home
        state: directory

    - name: Mount Home (new)
      mount:
        path: /home
        src: /dev/vg_nvme/lv_home
        fstype: ext4
        state: mounted
