---
- name: Disable IPv6 on Ubuntu 20.04
  hosts: all
  become: true
  vars:
    sysctl_config_file: /etc/sysctl.conf
    sysctl_config:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv6.conf.eth0.disable_ipv6: 1

  tasks:
    - name: Update sysctl values and reload if necessary
      ansible.posix.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: true
        state: present
        reload: true
        ignoreerrors: true
      with_dict: '{{ sysctl_config }}'
...
