- name: Enable sudo with no password for nvidia user
  hosts: all
  become: true
  tasks:
    - name: Ensure nvidia user exists
      ansible.builtin.user:
        name: nvidia
        state: present

    - name: Add nvidia user to sudo group
      ansible.builtin.user:
        name: nvidia
        groups: sudo
        append: true

    - name: Create sudoers file for nvidia user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/nvidia
        content: "nvidia ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Ensure the sudoers file has correct permissions
      ansible.builtin.file:
        path: /etc/sudoers.d/nvidia
        owner: root
        group: root
        mode: '0440'
...
