---
- name: Install NVIDIA Container Toolkit and Docker on Jetson
  hosts: all 
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
        state: present

    - name: Add NVIDIA Docker GPG key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present

    - name: Add NVIDIA Docker repository (arm64)
      apt_repository:
        repo: "deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/arm64 /"
        # repo: "deb https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list "
        state: present
        filename: nvidia-docker

    - name: Install nvidia-docker2
      apt:
        name: nvidia-docker2
        state: present

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    - name: Add nvidia user to docker group
      user:
        name: nvidia
        groups: docker
        append: yes

    - name: Print message
      debug:
        msg: "nvidia user has been added to the docker group. You may need to log out and log back in for the changes to take effect."

    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.13.5/install-guide.html#setting-up-docker
    - name: Add NVIDIA Container Toolkit repository key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        state: present

    - name: Add NVIDIA Container Toolkit repository (arm64)
      apt_repository:
        repo: "deb https://nvidia.github.io/libnvidia-container/stable/deb/arm64 /"
        # repo: "deb https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list "
        # repo: deb https://nvidia.github.io/nvidia-docker/l4t/stable r32.4 main
        # repo: "deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/arm64 /"
        state: present
        filename: nvidia-container-toolkit

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      apt:
        name:
          - nvidia-container-toolkit
        state: present

    - name: Run nvidia-ctk to configure Docker runtime
      command: nvidia-ctk runtime configure --runtime=docker
      register: nvidia_ctk_result
      changed_when: nvidia_ctk_result.rc != 0
      failed_when: false  # This prevents the playbook from failing if the command returns a non-zero exit code

    - name: Display nvidia-ctk output
      debug:
        var: nvidia_ctk_result.stdout_lines
      when: nvidia_ctk_result.stdout_lines is defined

    - name: Display nvidia-ctk error output
      debug:
        var: nvidia_ctk_result.stderr_lines
      when: nvidia_ctk_result.stderr_lines is defined

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    - name: Test NVIDIA Container Toolkit installation
      # command: docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
      command: docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi
      register: test_output
      changed_when: false

    - name: Display test output
      debug:
        var: test_output.stdout_lines
