---
- name: Install packages on Ubuntu
  hosts: all
  become: true  # This allows Ansible to use sudo

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: 'true'

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - autoconf
          - bc
          - build-essential
          - g++-8
          - gcc-8
          - clang-8
          - lld-8
          - gettext-base
          - gfortran-8
          - iputils-ping
          - libbz2-dev
          - libc++-dev
          - libcgal-dev
          - libffi-dev
          - libfreetype6-dev
          - libhdf5-dev
          - libjpeg-dev
          - liblzma-dev
          - libncurses5-dev
          - libncursesw5-dev
          - libpng-dev
          - libreadline-dev
          - libssl-dev
          - libsqlite3-dev
          - libxml2-dev
          - libxslt-dev
          - locales
          - moreutils
          - openssl
          - python-openssl
          - rsync
          - scons
          - python3-pip
          - libopenblas-dev
          - cmake
          - curl
        state: present

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: safe
...
