---
- name: Install NVIDIA Docker
  hosts: all
  become: yes
  tasks:
    - name: Add NVIDIA Docker GPG key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present

    - name: Add NVIDIA Docker repository
      apt_repository:
        repo: deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64 /
        state: present
        filename: nvidia-docker

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nvidia-docker2
      apt:
        name: nvidia-docker2
        state: present

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
