---
- name: Install K3s on Master Node
  hosts: xavier-01
  become: true
  tasks:
    - name: Download K3s installation script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: Install K3s on Master Node
      ansible.builtin.command: /tmp/k3s_install.sh
      environment:
        INSTALL_K3S_EXEC: "server"
      changed_when: false

    - name: Get K3s token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Store K3s token
      ansible.builtin.set_fact:
        k3s_node_token: "{{ k3s_token.stdout }}"

- name: Install K3s on Worker Nodes
  hosts: xavier-02,xavier-03
  become: true
  tasks:
    - name: Download K3s installation script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'
      changed_when: false

    - name: Install K3s on Worker Nodes
      ansible.builtin.command: /tmp/k3s_install.sh
      environment:
        K3S_URL: "https://{{ hostvars['xavier-01']['ansible_host'] }}:6443"
        K3S_TOKEN: "{{ hostvars['xavier-01']['k3s_node_token'] }}"
      changed_when: false

- name: Verify K3s Installation
  hosts: xavier-01
  become: true
  tasks:
    - name: Wait for nodes to be ready
      ansible.builtin.command: k3s kubectl get nodes
      register: node_status
      until: "'Ready' in node_status.stdout"
      retries: 10
      delay: 30
      changed_when: false
...
