---
- name: Configure Volumes, Filesystems, and Mounts
  hosts: all
  become: true
  tasks:

    - name: Create Logical Volume for Docker
      community.general.lvol:
        vg: vg_nvme
        lv: lv_docker
        size: 25g
        state: present

    - name: Create Logical Volume for Rancher
      community.general.lvol:
        vg: vg_nvme
        lv: lv_rancher
        size: 25g
        state: present

    - name: Create filesystem on lv_docker
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_docker

    - name: Create filesystem on lv_rancher
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_rancher

    - name: Create mount point for Docker
      ansible.builtin.file:
        path: /var/lib/docker
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create mount point for Rancher
      ansible.builtin.file:
        path: /var/lib/rancher
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Mount lv_docker
      ansible.posix.mount:
        path: /var/lib/docker
        src: /dev/vg_nvme/lv_docker
        fstype: ext4
        state: mounted

    - name: Mount lv_rancher
      ansible.posix.mount:
        path: /var/lib/rancher
        src: /dev/vg_nvme/lv_rancher
        fstype: ext4
        state: mounted
...
