---
- name: Configure Volume, Filesystem, and Mount for /home
  hosts: all
  become: yes
  tasks:

    - name: Create Logical Volume for Home
      lvol:
        vg: vg_nvme
        lv: lv_home
        size: 20g
        state: present

    - name: Create filesystem on lv_home
      filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_home

    - name: Create a temporary mount point
      file:
        path: /mnt/newhome
        state: directory

    - name: Mount lv_home in temporary filesystem
      mount:
        path: /mnt/newhome
        src: /dev/vg_nvme/lv_home
        fstype: ext4
        state: mounted

    - name: Copy multiple Directories
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        remote_src: yes
      with_items:
        - { src: '/home/',dest: '/mnt/newhome/',mode: preserve}

    - name: Unmount the temporary mount point
      mount:
        path: /mnt/newhome
        state: unmounted

    - name: Remove the temporary mount point
      file:
        path: /mnt/newhome
        state: absent

    - name: Backup original /home
      command: mv /home /home.bak

    - name: Create mount point for Home
      file:
        path: /home
        state: directory

    - name: Mount Home (new)
      mount:
        path: /home
        src: /dev/vg_nvme/lv_home
        fstype: ext4
        state: mounted
