---
- name: Configure Volume, Filesystem, and Mount for /opt
  hosts: all
  become: true
  tasks:
    - name: Create Logical Volume for Opt
      community.general.lvol:
        vg: vg_nvme
        lv: lv_opt
        size: 20g
        state: present

    - name: Create filesystem on lv_opt
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vg_nvme/lv_opt

    - name: Create a temporary mount point
      ansible.builtin.file:
        path: /mnt/newopt
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Mount lv_opt in temporary filesystem
      ansible.posix.mount:
        path: /mnt/newopt
        src: /dev/vg_nvme/lv_opt
        fstype: ext4
        state: mounted

    - name: Synchronize /home to new volume
      ansible.posix.synchronize:
        src: /opt/
        dest: /mnt/newopt/
        recursive: true
      delegate_to: "{{ inventory_hostname }}"

    - name: Unmount the temporary mount point
      ansible.posix.mount:
        path: /mnt/newopt
        state: unmounted

    - name: Remove the temporary mount point
      ansible.builtin.file:
        path: /mnt/newopt
        state: absent

    - name: Backup original /opt
      ansible.builtin.command: mv /opt /opt.bak
      register: opt_backed_up
      changed_when: opt_backed_up.rc != 0

    - name: Create mount point for Home
      ansible.builtin.file:
        path: /opt
        state: directory
        mode: '0755'
        owner: root
        group: root
    - name: Mount Home (new)
      ansible.posix.mount:
        path: /opt
        src: /dev/vg_nvme/lv_opt
        fstype: ext4
        state: mounted
...
