---
- name: Update /etc/hosts file
  hosts: all
  become: true  # Run tasks with sudo privileges
  gather_facts: true  # Gather facts about the target hosts

  tasks:
    - name: Determine hostname from inventory
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"
      register: hostname_result

    - name: Generate /etc/hosts entries
      ansible.builtin.set_fact:
        hosts_entries: "{{ hosts_entries | default([]) + ['%s %s %s' % (hostvars[item]['ansible_host'], item, hostvars[item]['inventory_hostname_short'])] }}"
      loop: "{{ groups['all'] }}"

    - name: Update /etc/hosts file
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          {% for entry in hosts_entries %}
          {{ entry }}
          {% endfor %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        state: present
...
